$(document).ready(function(){
    $('.slider').bxSlider({
        slideWidth:1200,
        pager:false,
        auto:true,
        stopAutoOnClick:true,
        pause:5000,
        speed:3000
    });
  });